---

- name: "Check if {{ hostname }}.qcow2 exists"
  delegate_to: localhost
  become: true
  stat:
    path: "/var/lib/libvirt/images/{{ hostname }}.qcow2"
  register: host_image_stat
  failed_when: host_image_stat.stat.exists

- name: Check if Fedora CoreOS qcow2 image exists
  delegate_to: localhost
  become: true
  stat:
    path: "/var/lib/libvirt/images/{{ fcos_image }}"
  register: fcos_image_stat
  failed_when: not fcos_image_stat.stat.exists

- name: Set CoreOS butane config
  delegate_to: localhost
  template:
    src: "templates/coreos-ignition.bu.j2"
    dest: "/tmp/hostname-ignition.bu"